// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package fr.ird.animat.server;

public final class Simulation_Stub
    extends java.rmi.server.RemoteStub
    implements fr.ird.animat.Simulation, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getEnvironment_0;
    private static java.lang.reflect.Method $method_getName_1;
    private static java.lang.reflect.Method $method_start_2;
    private static java.lang.reflect.Method $method_stop_3;
    
    static {
	try {
	    $method_getEnvironment_0 = fr.ird.animat.Simulation.class.getMethod("getEnvironment", new java.lang.Class[] {});
	    $method_getName_1 = fr.ird.animat.Simulation.class.getMethod("getName", new java.lang.Class[] {});
	    $method_start_2 = fr.ird.animat.Simulation.class.getMethod("start", new java.lang.Class[] {});
	    $method_stop_3 = fr.ird.animat.Simulation.class.getMethod("stop", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Simulation_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getEnvironment()
    public fr.ird.animat.Environment getEnvironment()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getEnvironment_0, null, 6556364000676045125L);
	    return ((fr.ird.animat.Environment) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getName()
    public java.lang.String getName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getName_1, null, 6317137956467216454L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of start()
    public void start()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_start_2, null, -8025343665958530775L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of stop()
    public void stop()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_stop_3, null, -2856118408655404442L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }

    public String getProperty(final String name)
	throws java.rmi.RemoteException
    {
        return null; // TODO: not yet implemented.
    }
}
