// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package fr.ird.animat.server;

public final class Species_Stub
    extends java.rmi.server.RemoteStub
    implements fr.ird.animat.Species, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getIcon_0;
    private static java.lang.reflect.Method $method_getLocales_1;
    private static java.lang.reflect.Method $method_getName_2;
    private static java.lang.reflect.Method $method_getObservedParameters_3;
    
    static {
	try {
	    $method_getIcon_0 = fr.ird.animat.Species.class.getMethod("getIcon", new java.lang.Class[] {});
	    $method_getLocales_1 = fr.ird.animat.Species.class.getMethod("getLocales", new java.lang.Class[] {});
	    $method_getName_2 = fr.ird.animat.Species.class.getMethod("getName", new java.lang.Class[] {java.util.Locale.class});
	    $method_getObservedParameters_3 = fr.ird.animat.Species.class.getMethod("getObservedParameters", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Species_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getIcon()
    public fr.ird.animat.Species.Icon getIcon()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getIcon_0, null, -4816147072875278455L);
	    return ((fr.ird.animat.Species.Icon) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getLocales()
    public java.util.Locale[] getLocales()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getLocales_1, null, 5249582721600285706L);
	    return ((java.util.Locale[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getName(Locale)
    public java.lang.String getName(java.util.Locale $param_Locale_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getName_2, new java.lang.Object[] {$param_Locale_1}, -397485419223841802L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getObservedParameters()
    public java.util.Set<fr.ird.animat.Parameter> getObservedParameters()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getObservedParameters_3, null, 5972150453383151269L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
